apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: p235uchcl-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/p235uchcl-dotnet-basic-gitops